### ISSUE TITLE
既然都做EXE了，不如来个GUI如何

### ISSUE THREAD

**Issue by NaughtDZ** [Ra1n-qwq/Stellaris_Mod_packing#1]
至少来点启动参数咋样，1.6版本默认是打包zip到D盘，但是我的装游戏的固态是H盘啊。
目前只能用１.５的PY文件自行改目标目录地址，但是新版本他不香嘛。

**Comment by Ra1n-qwq** [comment]
关于保存路径的问题，下个版本会做出来让用户选择路径的功能的。python的GUI界面没尝试过，需要从头开始学，可能需要一段时间。感谢你的宝贵意见~

**Comment by Ra1n-qwq** [comment]
新版本已经发布
